### ISSUE TITLE
Clicking the install button for the extension takes down the site

### ISSUE THREAD

**Issue by kbrabrand** [netliferesearch/craft-elastic#1]
![image](https://user-images.githubusercontent.com/2884292/29160795-f588b0fc-7db3-11e7-96e2-1d4a10bb46e3.png)

**Comment by kbrabrand** [comment]
This is caused by the plugin getting env vars (that could be undefined) and trying to parse null/falsy values as URIs. This fails with a fatal error when the `ELASTIC_HOSTS` env var is not set.

**Comment by phoob** [comment]
hmm. will have to figure out this later.. in another repo ;)
